services:
  smartdns:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: jeffok/smartdns:latest
    container_name: smartdns
    restart: always
    network_mode: "host"
    volumes:
      - ./data/rules:/etc/smartdns/rules
      - ./data/logs:/var/log/smartdns
    env_file: .env
